import { DateTimeImmutable } from "../types/date";

/**
 * This function class covers everything surrounding energy
 */
export const DateTimeImmutableToDate = (
  date: DateTimeImmutable | Date
): Date => {
  if (date instanceof Date) return date;
  return new Date(date.date + date.timezone);
};

export const DateToDateTimeImmutableNow = () => {
  return DateToDateTimeImmutable(new Date());
};

export const DateToDateTimeImmutable = (
  date: DateTimeImmutable | Date
): DateTimeImmutable => {
  if (typeof date === "object" && !(date instanceof Date)) {
    let dateTimeImmutable: DateTimeImmutable = {
      date: "",
      timezone: "",
      timezone_type: null,
    };
    if ("date" in date) dateTimeImmutable.date = date.date;
    if ("timezone" in date) dateTimeImmutable.timezone = date.timezone;
    if ("timezone_type" in date)
      dateTimeImmutable.timezone_type = date.timezone_type;
    if (dateTimeImmutable) return dateTimeImmutable;
    throw new Error("Unable to convert Date to DateTimeImmutable");
  }
  let actualDate = date as Date;
  let year = actualDate.getFullYear();
  let month = actualDate.getMonth() + 1;
  let day = actualDate.getDate();

  let hours = actualDate.getHours();
  let minutes = actualDate.getMinutes();
  let seconds = actualDate.getSeconds();

  let ms = actualDate.getMilliseconds();

  let tzPositive = 0 >= actualDate.getTimezoneOffset();
  let tzHour = Math.floor(Math.abs(actualDate.getTimezoneOffset() / -60));
  let tzMin = Math.floor(
    (Math.abs(actualDate.getTimezoneOffset() / 60) - tzHour) * 60
  );

  const dateTimeImmutable: DateTimeImmutable = {
    date:
      String(year).padStart(4, "0") +
      "-" +
      String(month).padStart(2, "0") +
      "-" +
      String(day).padStart(2, "0") +
      " " +
      String(hours).padStart(2, "0") +
      ":" +
      String(minutes).padStart(2, "0") +
      ":" +
      String(seconds).padStart(2, "0") +
      "." +
      ms.toString(),
    timezone:
      (tzPositive ? "+" : "-") +
      String(tzHour).padStart(2, "0") +
      ":" +
      String(tzMin).padStart(2, "0"),
    timezone_type: null,
  };
  return dateTimeImmutable;
};

/**
 * This code was generated by an deepseek https://chat.deepseek.com/a/chat/s/fdeff757-59e6-402a-b866-8d4c8c864a29
 * @param input Can either be epoch, Date or DateTimeImmutable
 * @param format short format only gives day + month + year, while long format gives everything down to the second
 */
export const prettyDateTime = (
  input: number | Date | DateTimeImmutable | undefined,
  format: "short" | "long" = "long"
): string => {
  if (input === undefined) {
    return "never";
  }
  // Convert input to Date object
  let date: Date;
  if (typeof input === "number") {
    date = new Date(input * 1000); // Convert epoch seconds to milliseconds
  } else if ("date" in input) {
    // DateTimeImmutable
    date = new Date(input.date);
  } else {
    // Date object
    date = input;
  }

  const now = new Date();
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);

  if (seconds < 10) {
    // Within 10 seconds - show full date/time
    return date
      .toISOString()
      .replace("T", " ")
      .replace(/\.\d+Z$/, "");
  } else if (seconds < 60) {
    // Within last minute
    const value = Math.max(1, seconds);
    return value === 1 ? "1 second ago" : `${value} seconds ago`;
  } else if (seconds < 60 * 60) {
    // Within last hour
    const minutes = Math.max(1, Math.floor(seconds / 60));
    return minutes === 1 ? "1 minute ago" : `${minutes} minutes ago`;
  } else if (seconds < 24 * 60 * 60) {
    // Within last day
    const hours = Math.max(1, Math.floor(seconds / (60 * 60)));
    return hours === 1 ? "1 hour ago" : `${hours} hours ago`;
  } else if (seconds < 3 * 24 * 60 * 60) {
    // Within last 3 days
    const days = Math.max(1, Math.floor(seconds / (24 * 60 * 60)));
    return days === 1 ? "1 day ago" : `${days} days ago`;
  } else if (format === "short") {
    // Short format
    const currentYear = new Date().getFullYear();
    if (date.getFullYear() === currentYear) {
      // Same year - show day and month
      return date.toLocaleDateString("en-US", {
        day: "numeric",
        month: "short",
      });
    } else {
      // Different year - show day, month and year
      return date.toLocaleDateString("en-US", {
        day: "numeric",
        month: "short",
        year: "numeric",
      });
    }
  } else {
    // Default format - day, month, year, time
    return date
      .toLocaleString("en-US", {
        day: "numeric",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
        hour12: false,
      })
      .replace(/,/g, "");
  }
};

export const getEpoch = () => {
  let epoch = new Date().getTime();
  epoch /= 1000;
  return epoch;
};
